// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckGameDir(arg1:string):Promise<boolean>;

export function GetConfig():Promise<main.ConfigType>;

export function GetContext(arg1:string):Promise<any>;

export function GetDisks():Promise<{[key: string]: number}>;

export function GetGameDir():Promise<Array<string>>;

export function ListDir(arg1:string):Promise<Array<main.FileInfo>>;

export function SetConfig(arg1:main.ConfigType):Promise<void>;

export function SetContext(arg1:string,arg2:any):Promise<void>;
