// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGameDir(arg1) {
  return window['go']['main']['App']['CheckGameDir'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContext(arg1) {
  return window['go']['main']['App']['GetContext'](arg1);
}

export function GetDisks() {
  return window['go']['main']['App']['GetDisks']();
}

export function GetGameDir() {
  return window['go']['main']['App']['GetGameDir']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SetContext(arg1, arg2) {
  return window['go']['main']['App']['SetContext'](arg1, arg2);
}
